/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifiers for the message or the thread.
 */
export type MsgId = string;
/**
 * The query that was posed to the tool.
 */
export type UserId = string;
/**
 * The name of the section
 */
export type Name = string;
/**
 * The index of the section
 */
export type Idx = number;
/**
 * The text of the section
 */
export type SectionFeedbackType = "text" | "table";
/**
 * The feedback provided by the user
 */
export type Feedback1 = string | null;

export interface Feedback {
  msg_id: MsgId;
  user_id: UserId;
  /**
   * Section metadata the feedback is for
   */
  section?: SectionFeedbackMetadata | null;
  feedback?: Feedback1;
  [k: string]: unknown;
}
export interface SectionFeedbackMetadata {
  name: Name;
  idx: Idx;
  fb_type?: SectionFeedbackType;
  [k: string]: unknown;
}
