version: "3.8"

services:
  # Load balancer
  nginx-lb:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./proxy/load-balancer.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-1
      - api-2
      - api-3

  # Multiple API instances for parallel processing
  api-1:
    build: ./api
    environment:
      - CONFIG_PATH=run_configs/default.json
      - WORKER_ID=1
    volumes:
      - ./api:/app
      - ./api/logs:/app/logs
    expose:
      - "8000"

  api-2:
    build: ./api
    environment:
      - CONFIG_PATH=run_configs/default.json
      - WORKER_ID=2
    volumes:
      - ./api:/app
      - ./api/logs:/app/logs
    expose:
      - "8000"

  api-3:
    build: ./api
    environment:
      - CONFIG_PATH=run_configs/default.json
      - WORKER_ID=3
    volumes:
      - ./api:/app
      - ./api/logs:/app/logs
    expose:
      - "8000"

  # Dedicated reranker service
  reranker:
    build:
      context: ./api
      dockerfile: Dockerfile.reranker
    environment:
      - MODEL_NAME=mixedbread-ai/mxbai-rerank-large-v1
      - BATCH_SIZE=32
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          memory: 8G

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules

  sonar:
    build: ./sonar
    ports:
      - "8888:8888"
