version: "3.8"
services:
  sonar:
    build: ./sonar
    depends_on:
      - api
      - ui
      - proxy
  api:
    build: ./api
    volumes:
      - ./api:/api
      - ./secret:/secret
    environment:
      # This ensures that errors are printed as they occur, which
      # makes debugging easier.
      - PYTHONUNBUFFERED=1
      - LITELLM_LOG=WARNING
      - CONFIG_PATH=run_configs/default.json
      # url of remote reranker service to be reached by the API container
      - RERANKER_SERVICE_URL=http://host.docker.internal:${RERANKER_PORT:-8001}
    extra_hosts:
      # This allows the API container to reach the reranker service
      # running on the host machine.
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:8000
    env_file:
      - .env
  ui:
    build: ./ui
    # We can't mount the entire UI directory, since JavaScript dependencies
    # (`node_modules`) live at that location.
    volumes:
      - ./ui/src:/ui/src
      - ./ui/public:/ui/public
      - ./ui/package.json:/ui/package.json
      - ./ui/yarn.lock:/ui/yarn.lock
      - ./ui/tsconfig.json:/ui/tsconfig.json
    environment:
      - NODE_ENV=development
    ports:
      - 4000:3000
  proxy:
    build: ./proxy
    ports:
      - 8080:8080
    depends_on:
      - ui
      - api
