version: "3"
services:
  sonar:
    build: ./sonar
    depends_on:
      - api
      - ui
      - proxy
  api:
    build: ./api
    volumes:
      - ./api:/api
      - ./secret:/secret
    environment:
      # This ensures that errors are printed as they occur, which
      # makes debugging easier.
      - PYTHONUNBUFFERED=1
      - LITELLM_LOG=WARNING
      - CONFIG_PATH=run_configs/default.json
      # Reranker service configuration
      - RERANKER_SERVICE_PORT=8002 # Internal container port for docker network
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - reranker
  ui:
    build: ./ui
    # We can't mount the entire UI directory, since JavaScript dependencies
    # (`node_modules`) live at that location.
    volumes:
      - ./ui/src:/ui/src
      - ./ui/public:/ui/public
      - ./ui/package.json:/ui/package.json
      - ./ui/yarn.lock:/ui/yarn.lock
      - ./ui/tsconfig.json:/ui/tsconfig.json
    environment:
      - NODE_ENV=development
    ports:
      - 4000:3000
  proxy:
    build: ./proxy
    ports:
      - 8080:8080
    depends_on:
      - ui
      - api
  reranker:
    build:
      context: ./reranker_service
      dockerfile: Dockerfile
    container_name: reranker-service
    ports:
      - "8001:8002" # Map external 8001 to internal 8002
    restart: unless-stopped
    environment:
      - PORT=8002
      - HOST=0.0.0.0
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: "2.0"
        reservations:
          memory: 4G
          cpus: "1.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
