# nginx.conf acts as a reverse proxy for the Solace AI prototype, managing traffic for the app.
# It receives all incoming requests and routes them to the appropriate services.
# It can  handle load balancing, security headers, gzip compression, and hiding server details.
user              nginx;
worker_processes  auto;

pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    # Accept the X-Forwarded-For header from all clients. By default NGINX discards the
    # header.
    set_real_ip_from    0.0.0.0/0;
    real_ip_header      X-Forwarded-For;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile            on;
    keepalive_timeout   65;

    gzip  on;

    server_tokens off;

    include /etc/nginx/conf.d/*;

    access_log off;
}
